build-ClientIndex:
	PAGE=index ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-ClientExample:
	PAGE=example ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-Client404:
	PAGE=404 ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-ClientPrivacy:
	PAGE=privacy ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-ClientError:
	PAGE=_error ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-ClientApp:
	PAGE=_app ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh

build-ClientDocument:
	PAGE=_document ARTIFACTS_DIR=$(ARTIFACTS_DIR) ./build-page.sh
