import {
	container,
	defaultFont,
	primaryColor,
	infoColor,
	successColor,
	warningColor,
	dangerColor,
	roseColor,
	transition,
	drawerWidth,
} from "assets/jss/nextjs-material-kit.js";

import tooltip from "assets/jss/nextjs-material-kit/tooltipsStyle.js";

const headerStyle = (theme) => ({
	appBar: {
		display: "flex",
		border: "0",
		borderRadius: "3px",
		marginBottom: "20px",
		color: "#555",
		width: "100%",
		backgroundColor: "#393e46",
		transition: "all 150ms ease 0s",
		alignItems: "center",
		flexFlow: "row nowrap",
		justifyContent: "flex-start",
		position: "relative",
		zIndex: "unset",
	},
	absolute: {
		position: "absolute",
		zIndex: "1100",
	},
	fixed: {
		position: "fixed",
		zIndex: "1100",
	},
	container: {
		...container,
		minHeight: "50px",
		flex: "1",
		alignItems: "center",
		justifyContent: "space-between",
		display: "flex",
		flexWrap: "nowrap",
	},
	flex: {
		flex: 1,
		textAlign: "left",
	},
	title: {
		...defaultFont,
		lineHeight: "30px",
		fontSize: "18px",
		borderRadius: "3px",
		textTransform: "none",
		color: "inherit",
		padding: "8px 16px",
		letterSpacing: "unset",
		"&:hover,&:focus": {
			color: "inherit",
			background: "transparent",
		},
	},
	appResponsive: {
		margin: "20px 10px",
	},
	primary: {
		backgroundColor: primaryColor,
		color: "#FFFFFF",
	},
	info: {
		backgroundColor: infoColor,
		color: "#FFFFFF",
	},
	success: {
		backgroundColor: successColor,
		color: "#FFFFFF",
	},
	warning: {
		backgroundColor: warningColor,
		color: "#FFFFFF",
	},
	danger: {
		backgroundColor: dangerColor,
		color: "#FFFFFF",
	},
	rose: {
		backgroundColor: roseColor,
		color: "#FFFFFF",
	},
	transparent: {
		backgroundColor: "transparent !important",
		boxShadow: "none",
		paddingTop: "25px",
		color: "#FFFFFF",
	},
	dark: {
		color: "#FFFFFF",
		backgroundColor: "#212121 !important",
	},
	white: {
		border: "0",
		padding: "0.625rem 0",
		marginBottom: "20px",
		color: "#555",
		backgroundColor: "#fff !important",
	},
	drawerPaper: {
		border: "none",
		bottom: "0",
		transitionProperty: "top, bottom, width",
		transitionDuration: ".2s, .2s, .35s",
		transitionTimingFunction: "linear, linear, ease",
		width: drawerWidth,
		position: "fixed",
		display: "block",
		top: "0",
		height: "100vh",
		right: "0",
		left: "auto",
		visibility: "visible",
		overflowY: "visible",
		borderTop: "none",
		textAlign: "left",
		paddingRight: "0px",
		paddingLeft: "0",
		...transition,
	},
	list: {
		...defaultFont,
		fontSize: "14px",
		margin: 0,
		paddingLeft: "0",
		listStyle: "none",
		paddingTop: "0",
		paddingBottom: "0",
		color: "inherit",
	},
	listItem: {
		float: "left",
		color: "inherit",
		position: "relative",
		display: "block",
		width: "auto",
		margin: "0",
		padding: "0",
		[theme.breakpoints.down("sm")]: {
			width: "100%",
			"&:after": {
				width: "calc(100% - 30px)",
				content: '""',
				display: "block",
				height: "1px",
				marginLeft: "15px",
				backgroundColor: "#e5e5e5",
			},
		},
	},
	listItemText: {
		padding: "0 !important",
	},
	navLink: {
		color: "inherit",
		position: "relative",
		padding: "0.9375rem",
		fontWeight: "400",
		fontSize: "16px",
		textTransform: "uppercase",
		borderRadius: "3px",
		lineHeight: "20px",
		textDecoration: "none",
		margin: "0px",
		display: "inline-flex",
		"&:hover,&:focus": {
			color: "inherit",
			background: "rgba(200, 200, 200, 0.2)",
		},
		[theme.breakpoints.down("sm")]: {
			width: "calc(100% - 30px)",
			marginLeft: "15px",
			marginBottom: "8px",
			marginTop: "8px",
			textAlign: "left",
			"& > span:first-child": {
				justifyContent: "flex-start",
			},
		},
	},
	notificationNavLink: {
		[theme.breakpoints.down("md")]: {
			top: "0",
			margin: "5px 15px",
		},
		color: "#FFF",
		padding: "0.9375rem",
		fontWeight: "400",
		fontSize: "12px",
		textTransform: "uppercase",
		lineHeight: "20px",
		textDecoration: "none",
		margin: "0px",
		display: "inline-flex",
		top: "4px",
	},
	registerNavLink: {
		[theme.breakpoints.down("md")]: {
			top: "0",
			margin: "5px 15px",
		},
		top: "3px",
		position: "relative",
		fontWeight: "400",
		fontSize: "12px",
		textTransform: "uppercase",
		lineHeight: "20px",
		textDecoration: "none",
		margin: "0px",
		display: "inline-flex",
	},
	navLinkActive: {
		color: "inherit",
		backgroundColor: "rgba(255, 255, 255, 0.1)",
	},
	icons: {
		width: "20px",
		height: "20px",
		marginRight: "3px",
	},
	socialIcons: {
		position: "relative",
		fontSize: "20px !important",
		marginRight: "4px",
	},
	dropdownLink: {
		"&,&:hover,&:focus": {
			color: "inherit",
			textDecoration: "none",
			display: "block",
			padding: "10px 20px",
		},
	},
	...tooltip,
	marginRight5: {
		marginRight: "5px",
	},
});

export default headerStyle;
